'use strict';

const { SlashCommandBuilder, PermissionFlagsBits } = require('discord.js');

const modCommand = new SlashCommandBuilder()
  .setName('mod')
  .setDescription('General server moderation tools.')
  .setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers)
  .addSubcommand(sc => sc.setName('config').setDescription('Set or view the moderation log channel.')
    .addChannelOption(o => o.setName('channel').setDescription('Channel for mod logs, e.g. bot-commands').setRequired(false)))
  .addSubcommand(sc => sc.setName('warn').setDescription('Log a warning for a user.')
    .addUserOption(o => o.setName('user').setDescription('User to warn').setRequired(true))
    .addStringOption(o => o.setName('reason').setDescription('Reason').setRequired(false).setMaxLength(900)))
  .addSubcommand(sc => sc.setName('timeout').setDescription('Timeout a member for a number of minutes.')
    .addUserOption(o => o.setName('user').setDescription('User to timeout').setRequired(true))
    .addIntegerOption(o => o.setName('minutes').setDescription('Timeout length in minutes').setRequired(true).setMinValue(1).setMaxValue(40320))
    .addStringOption(o => o.setName('reason').setDescription('Reason').setRequired(false).setMaxLength(900)))
  .addSubcommand(sc => sc.setName('untimeout').setDescription('Remove a timeout from a member.')
    .addUserOption(o => o.setName('user').setDescription('User to remove timeout from').setRequired(true))
    .addStringOption(o => o.setName('reason').setDescription('Reason').setRequired(false).setMaxLength(900)))
  .addSubcommand(sc => sc.setName('kick').setDescription('Kick a member.')
    .addUserOption(o => o.setName('user').setDescription('User to kick').setRequired(true))
    .addStringOption(o => o.setName('reason').setDescription('Reason').setRequired(false).setMaxLength(900)))
  .addSubcommand(sc => sc.setName('ban').setDescription('Ban a user.')
    .addUserOption(o => o.setName('user').setDescription('User to ban').setRequired(true))
    .addIntegerOption(o => o.setName('delete_messages_hours').setDescription('Delete recent messages, 0-168 hours').setRequired(false).setMinValue(0).setMaxValue(168))
    .addStringOption(o => o.setName('reason').setDescription('Reason').setRequired(false).setMaxLength(900)))
  .addSubcommand(sc => sc.setName('unban').setDescription('Unban a user by Discord user ID.')
    .addStringOption(o => o.setName('user_id').setDescription('Discord user ID').setRequired(true))
    .addStringOption(o => o.setName('reason').setDescription('Reason').setRequired(false).setMaxLength(900)))
  .addSubcommand(sc => sc.setName('purge').setDescription('Delete recent messages in this channel.')
    .addIntegerOption(o => o.setName('amount').setDescription('Number of recent messages to scan, max 100').setRequired(true).setMinValue(1).setMaxValue(100))
    .addUserOption(o => o.setName('user').setDescription('Only delete messages from this user').setRequired(false))
    .addStringOption(o => o.setName('reason').setDescription('Reason').setRequired(false).setMaxLength(900)))
  .addSubcommand(sc => sc.setName('slowmode').setDescription('Set channel slowmode.')
    .addIntegerOption(o => o.setName('seconds').setDescription('Slowmode seconds, 0 disables it').setRequired(true).setMinValue(0).setMaxValue(21600))
    .addChannelOption(o => o.setName('channel').setDescription('Channel, defaults to current').setRequired(false))
    .addStringOption(o => o.setName('reason').setDescription('Reason').setRequired(false).setMaxLength(900)))
  .addSubcommand(sc => sc.setName('lock').setDescription('Stop @everyone from sending messages in a channel.')
    .addChannelOption(o => o.setName('channel').setDescription('Channel, defaults to current').setRequired(false))
    .addStringOption(o => o.setName('reason').setDescription('Reason').setRequired(false).setMaxLength(900)))
  .addSubcommand(sc => sc.setName('unlock').setDescription('Remove the HashGoblin channel lock from a channel.')
    .addChannelOption(o => o.setName('channel').setDescription('Channel, defaults to current').setRequired(false))
    .addStringOption(o => o.setName('reason').setDescription('Reason').setRequired(false).setMaxLength(900)))
  .addSubcommand(sc => sc.setName('cases').setDescription('Show recent moderation cases.')
    .addUserOption(o => o.setName('user').setDescription('Only show cases for this user').setRequired(false)));

module.exports = [modCommand];
